name: fingerprint bot

on:
  issue_comment:                                     
    types: [created, edited, deleted]

env:
  RUN: docker run --shm-size 1G -v $PWD:/tmp/openpilot -w /tmp/openpilot -e PYTHONWARNINGS=error -e FILEREADER_CACHE=1 -e PYTHONPATH=/tmp/openpilot -e NUM_JOBS -e JOB_ID -e GITHUB_ACTION -e GITHUB_REF -e GITHUB_HEAD_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -v $GITHUB_WORKSPACE/.ci_cache/scons_cache:/tmp/scons_cache -v $GITHUB_WORKSPACE/.ci_cache/comma_download_cache:/tmp/comma_download_cache -v $GITHUB_WORKSPACE/.ci_cache/openpilot_cache:/tmp/openpilot_cache $BASE_IMAGE /bin/sh -c

jobs:
  fingerprint:
    if: contains(github.event.comment.body, '/fingerprint')
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/workflows/setup-with-retry
      - name: fingerprint
        run: |
          ${{ env.RUN }} python selfdrive/debug/ci_fingerprint.py ${{ github.event.comment.body }}
      - name: create branch
        run: |
          git add .
          git commit -m '{{ steps.fingerprint.pr-title }}'
          git push -u origin {{ steps.fingerprint.pr-branch-name }}
      - name: create pull request
        run: gh pr create -B master -H {{ steps.fingerprint.pr-branch-name }} --title '{{ steps.fingerprint.pr-title }}' --body '{{ steps.fingerprint.pr-comment }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}