name: fingerprint bot

on:
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
  fingerprint:
    if: contains(github.event.comment.body, '/fingerprint')
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/workflows/setup-with-retry
      - name: fingerprint
      - name: create pull request
        run: gh pr create -B base_branch -H branch_to_merge --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}